# Generated by Django 6.0.1 on 2026-01-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название города')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Район / часть области')),
                ('short_description', models.TextField(help_text='1–2 абзаца', verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
