# Generated by Django 6.0.1 on 2026-01-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='Фото города'),
        ),
        migrations.AddField(
            model_name='citycard',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='citycard',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
