# Generated by Django 6.0.1 on 2026-01-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_citycard_image_citycard_lat_citycard_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycard',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Население'),
        ),
    ]
