# Generated by Django 6.0.1 on 2026-01-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_citycard_population_alter_citycard_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycard',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
