# Generated by Django 6.0.1 on 2026-02-01 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_citycard_population_alter_citycard_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citycard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='citycard',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='city_images/'),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='region',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
