# Generated by Django 6.0.1 on 2026-02-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_citycard_updated_at_citycard_views_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citycard',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='citycard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/'),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='region',
            field=models.CharField(max_length=200, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='citycard',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
    ]
